import 'package:flutter/material.dart';
class ColorsClass {
  
List<Color> colorss = [
    Colors.yellow,
    Colors.red,
    Colors.pink,
    Colors.purple,
    Colors.cyan,
    Colors.teal,
    Colors.brown,
    Colors.lightBlue,
    Colors.deepOrange,
    Colors.grey,
    Colors.blueGrey,
    Colors.amber,
    Colors.deepPurple,
    Colors.green,
    Colors.lightGreen,
    Colors.teal,
    Colors.deepOrange,
    Colors.brown,
    Colors.pink,
    Colors.purple,
    Colors.deepPurple,
    Colors.cyan,
    Colors.lightBlue,
    Colors.lightGreen,
    Colors.amber,
    Colors.orange,
    Colors.brown,
    Colors.grey,
    Colors.blueGrey,
    Colors.pink,
    Colors.purple,
    Colors.deepPurple,
    Colors.cyan,
];
}